name: Generate and publish

on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_MACHINE_TOKEN }}
          publish_dir: .output/public
